Connected = False
counter=0

while not Connected and (counter<5):
	Connected=socket_open("192.168.0.5", 13000, "Google_Firebase_Socket")
	counter=counter+1
end
if counter>=5:
	popup("Connection to fireBaseSocket failed","Time out",False,True,blocking=True)
	halt
else:
	popup("Connected to fireBaseSocket","GOOD NEWS",False,False,blocking=True)
end

while True:
	popup("Initiate instructions to move LEFT and update Firebase","ALERT",False,True,blocking=True)
	socket_send_string("moveLeft", "Google_Firebase_Socket")
	movej(p[-0.13776,0.01691,0.46656,0.0649,-0.0398,-0.4431],a=1.2,v=1,r=0)
	
	popup("Initiate instructions to move RIGHT and update Firebase","ALERT",False,True,blocking=True)
	socket_send_string("moveRight", "Google_Firebase_Socket")
	movej(p[-0.04463,0.11323,0.69341,4.0165,-2.4579,2.7093],a=1.2,v=1,r=0)
end